export const fonts = [
    { id: 1, name: 'Times New Roman' },
    { id: 2, name: 'Alfa Frivolity Bold' },
    { id: 3, name: 'Amazone 0123456789' },
    { id: 4, name: 'Amarante normal' },
    { id: 5, name: 'Arial Black Bold' },
    { id: 6, name: 'Amatic SC bold' },
    { id: 7, name: 'Baloo Bhaina Normal' },
    { id: 8, name: 'Bangers Norma' },
    { id: 9, name: 'Dauphin CE' },
    { id: 10, name: 'Berkshire Swash Normal' },
    { id: 11, name: 'Black Ops One' },
    { id: 12, name: 'BLADE RUNNER MOVIE' },
    { id: 13, name: 'Bree Serif' },
    { id: 14, name: 'CANCUN' },
    { id: 15, name: 'Capriola' },
    { id: 16, name: 'Caveat Brush' },
    { id: 17, name: 'Comic Sans' },
    { id: 19, name: 'Cormorant Bold' },
    { id: 20, name: 'Cyrilic Old Latin' },
    { id: 21, name: 'Dancing Script' },
    { id: 22, name: 'Freckle Face Bold' },
    { id: 23, name: 'Galindo' },
    { id: 24, name: 'Georgia Bold' },
    { id: 25, name: 'Ginko Ce' },
    { id: 26, name: 'Great Vibes' },
    { id: 27, name: 'Hanalei fill' },
    { id: 28, name: 'Impact' },
    { id: 29, name: 'Jockey One' },
    { id: 30, name: 'Jokerman' },
    { id: 31, name: 'Joti One' },
    { id: 32, name: 'Just Me Again Down Here' },
    { id: 33, name: 'Kalam Bold' },
    { id: 34, name: 'Kaushan Script' },
    { id: 35, name: 'Kavoon' },
    { id: 36, name: 'Kelly Slab' },
    { id: 37, name: 'Kids' },
    { id: 38, name: 'Marcellus sc' },
    { id: 39, name: 'Margarine' },
    { id: 40, name: 'metrolox' },
    { id: 41, name: 'Mogra' },
    { id: 42, name: 'Monotype Corsiva' },
    { id: 43, name: 'Mouse Memoirs' },
    { id: 44, name: 'New Rocker' },
    { id: 45, name: 'Octin prison free' },
    { id: 46, name: 'Old English' },
    { id: 47, name: 'Oregano' },
    { id: 48, name: 'Parisienne' },
    { id: 49, name: 'Patrick Hand' },
    { id: 50, name: 'Signet Roundhand' },
    { id: 51, name: 'Snap ITC' },
    { id: 52, name: 'stAMP' },
  ]